version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Installing dependancies..."
      - yarn
  build:
    commands:
      - echo "Executing ${ENV} environment"
      - echo "Run application tests"
      - CI=true npm test
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo "Copy the contents of build to destination S3 bucket"
      - aws s3 cp --recursive --acl public-read ./build s3://$S3_BUCKET_DESTINATION/
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"
    - "/root/.yarn-cache/**/*"
